### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by leynebe** [sailthru/terraform-aws-secretsmanager-data#3]
I understand that the secret is output to the echo command, but how does that all of a sudden result in Terraform being able to map it?

Thanks!

**Comment by moskyb** [comment]
Hey @leynebe - sorry it's taken so long to get to your issue.

Prior to terraform 0.12 (which wasn't GA at the time of release of this module), there wasn't a native way for Terraform to take a JSON string and decode it into a terraform map. To work around this, we used the [Terraform External Data Source](https://www.terraform.io/docs/providers/external/data_source.html). An external data source allows you to pass data to an external function (in this case, simply `echo`), and whatever that function outputs to STDOUT, so long as its parsable json, is imported back into Terraform as an attribute of the data source.

Once we updgrade to Terraform 0.12, this hacky workaround won't be necessary anymore - we'll be able to just call something like 
```HCL
output "secret_map" {
  value = jsondecode("data.aws_secretsmanager_secret_version.this.secret_string")
}
```

Which will return the json of your AWS secret as a native Terraform map.

Let me know if this has made things clearer for you and I'll close the issue :)

**Comment by leynebe** [comment]
I was just curious because even carefully analyzing the code I couldn't understand what was happening. We upgraded to 0.12 already but we've used this code extensively so thank you very much for that!
